const types = {
    GET_MY_FOLLOWERS_REQUEST: 'GET_MY_FOLLOWERS_REQUEST',
    GET_MY_FOLLOWERS_SUCCESS: 'GET_MY_FOLLOWERS_SUCCESS',
    GET_MY_FOLLOWERS_FAILURE: 'GET_MY_FOLLOWERS_FAILURE',
    GET_SINGLE_FOLLOWER_REQUEST: "GET_SINGLE_FOLLOWER_REQUEST",
    GET_SINGLE_FOLLOWER_SUCCESS: "GET_SINGLE_FOLLOWER_SUCCESS",
    GET_SINGLE_FOLLOWER_FAILURE: "GET_SINGLE_FOLLOWER_FAILURE",
    GET_PEOPLE_I_FOLLOW_REQUEST: 'GET_PEOPLE_I_FOLLOW_REQUEST',
    GET_PEOPLE_I_FOLLOW_SUCCESS: 'GET_PEOPLE_I_FOLLOW_SUCCESS',
    GET_PEOPLE_I_FOLLOW_FAILURE: 'GET_PEOPLE_I_FOLLOW_FAILURE',
}


export default types